site_url: https://ntn-boilerplate.netlify.app/
logo_url: https://ntn-boilerplate.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

i18n:
  structure: multiple_folders
  locales: [en, de, ua]
  default_locale: en

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
#  - name: 'navigation'
#    label: 'Navigation'
#    folder: '/content'
#    format: json
#    i18n: false
#    fields:
#      - { label: 'Items', name: items, widget: list, default: ['/pages/home', '/projects', '/pages/get-involved', '/blog', '/pages/contact']}
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    format: 'frontmatter'
    slug: '{{fields.createdAt}}-{{slug}}'
    i18n: true
    editor:
      preview: true
    fields:
      - { label: 'Created Date', name: 'createdAt', widget: 'datetime', date_format: "YYYY-MM-DD", time_format: false, i18n: false }
      - { label: 'Title', name: 'title', widget: 'string', required: true, i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false, i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false, i18n: true }
      - { label: 'Image', name: 'image', widget: 'image', required: false, allow_multiple: false, i18n: false }
  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    folder: 'content/projects'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    i18n: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true, i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false, i18n: true }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false, i18n: false }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false, i18n: true }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          i18n: false,
          field: { label: 'Image', name: 'image', widget: 'image', i18n: false },
        }
  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages'
    create: true
    format: 'frontmatter'
    slug: '{{fields.createdAt}}-{{slug}}'
    i18n: true
    editor:
      preview: true
    fields:
      - { label: 'Created Date', name: 'createdAt', widget: 'datetime', date_format: "YYYY-MM-DD", time_format: false, i18n: false }
      - { label: 'Title', name: 'title', widget: 'string', required: true, i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false, i18n: true }
